### ISSUE TITLE
Update pipeline to use Azure and auto-sign launcher

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer-desktop-launcher#119]

**Comment by aixaCode** [comment]
Yes, it is. Currently, to release a Launcher version, we need a manual step from @olavra or @kuruk-mm because we have the private keys to sign the Launcher executable.
We wanted to add the private key to GitHub Action, but Mendez said no. Because it’s a security problem, someone with permission to GitHub can reach that key and sign for us.
So Azure Pipelines can run GitHub Actions but in private in their Cloud. So the idea is to put the Private Key there and execute the CI there in private from the public repo.

**Comment by 2fd** [comment]
moved to decentraland/unity-renderer#1045
